CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    salt VARCHAR(64) NOT NULL,
    hash_senha VARCHAR(100) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alunos (
    id UUID PRIMARY KEY,
    matricula VARCHAR(50) UNIQUE NOT NULL,
    media NUMERIC(5,2) NOT NULL DEFAULT 0,
    data_inicio DATE NOT NULL,
    data_conclusao DATE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
