CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    salt VARCHAR(64) NOT NULL,
    hash_senha VARCHAR(100) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alunos (
    id UUID PRIMARY KEY,
    matricula VARCHAR(50) UNIQUE NOT NULL,
    media NUMERIC(5,2) NOT NULL DEFAULT 0,
    data_inicio DATE NOT NULL,
    data_conclusao DATE,
    usuario_id UUID NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS professores (
    id UUID PRIMARY KEY,
    area VARCHAR(100) NOT NULL,
    usuario_id UUID NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avaliacoes (
    id UUID PRIMARY KEY,
    descricao TEXT NOT NULL,
    data DATE NOT NULL,
    horario TIME NOT NULL,
    professor_id UUID REFERENCES professores(id) ON DELETE SET NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avaliacao_alunos (
    avaliacao_id UUID REFERENCES avaliacoes(id) ON DELETE CASCADE,
    aluno_id UUID REFERENCES alunos(id) ON DELETE CASCADE,
    nota NUMERIC(5,2),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (avaliacao_id, aluno_id)
);
